[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "gist-memory"
version = "0.1.0"
description = "Prototype implementation of the Gist Memory Agent"
authors = [{name = "Scott Falconer", email = "scottfalconer@gmail.com"}]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openai",
    "tiktoken",
    "numpy",
    "faiss-cpu",
    "click",
    "tqdm",
    "pydantic",
    "pyyaml",
    "sentence-transformers",
    "nltk",
    "typer[all]",
    "portalocker",
    "textual>=0.46",
    "rich>=13.6",
]

[project.optional-dependencies]
test = ["pytest"]
chroma = ["chromadb"]
tui = ["textual>=0.46", "rich>=13.6"]

[project.scripts]
gist-memory = "gist_memory.__main__:main"
gist-run = "gist_tui.__main__:main"
