[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "gist-memory"
version = "0.1.0"
description = "Prototype implementation of the Gist Memory Agent"
authors = [{name = "Scott Falconer", email = "scottfalconer@gmail.com"}]
license = {text = "MIT"}
readme = "README.md"
dependencies = [
    "openai",
    "tiktoken",
    "numpy",
    "faiss-cpu",
    "click>=8.2",
    "tqdm",
    "pydantic",
    "pyyaml",
    "sentence-transformers",
    "transformers",
    "spacy",
    "typer[all]>=0.16.0",
    "portalocker",
    "rich>=13.6",
    "google-generativeai",
    "evaluate",
]

[project.optional-dependencies]
test = ["pytest"]
chroma = ["chromadb"]
spacy = ["spacy"]
optuna = ["optuna"]
ray = ["ray[tune]"]

[project.scripts]
gist-memory = "gist_memory.__main__:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["gist_memory", "gist_memory.*"]

[tool.setuptools.package-data]
"gist_memory" = ["py.typed"]
